### ISSUE TITLE
Plugin Directory Copy

### ISSUE THREAD

**Issue by willmot** [humanmade/godaddy-email-marketing-wordpress-plugin#1]
- [ ] What should it be officially called? Mad Mimi's is:
> Official Mad Mimi Sign Up Forms

- [ ] What should the plugin description be, Mad Mimi's is:
> Add your Mad Mimi webform to your WordPress site! Easy to set up, the Mad Mimi plugin allows your site visitors to subscribe to your email lists.

- [ ] Readme, Mad Mimi's is:

> The Official Mad Mimi Sign Up Form plugin makes it easy to grow your subscribers! Use this plugin to integrate your email newsletter sign up forms into your WordPress site. If you'd like to learn more about Mad Mimi, grab a [FREE forever account](http://madmimi.com/) and explore.
>
>Once the plugin is activated, you'll be able to select and insert any of your Mad Mimi webforms right into your site by using a widget, shortcode, or template tag. Setup is easy. In Settings, simply enter your account email address and API key (found in your [Mad Mimi account](http://help.madmimi.com/where-can-i-find-my-api-key/) area) and you're all set.
>
>Official Mad Mimi Forms Plugin Features:
>
> - Automatically add new forms for users to sign up to an email list of your choice
> - Unlimited signup forms by using the widget, shortcode, or template tag
> - Quick links to preview your form in Mad Mimi
> - Quick links to edit your form in Mad Mimi

- [ ] Plugin Tags, Mad Mimi's are:

> forms, newsletter, opt-in

- [ ] Installation instructions, Mad Mimi's are:

> 1. Upload plugin files to your plugins folder, or install using WordPress' built-in Add New Plugin installer
> 2. Activate the plugin
> 3. Go to the plugin settings page (under Settings > Mad Mimi Settings)
> 4. Simply enter your account email address and API key (found in your [Mad Mimi account](http://help.madmimi.com/where-can-i-find-my-api-key/) area).
> 5. Click Save Changes.
>
> Once your account is verified, you can insert a form into your site by using a widget, shortcode, or template tag: 
> * Widget: Go to Appearance > Widgets and find the widget called “Mad Mimi Form” and drag it into the widget area of your choice. You can then add a title and select a form! 
> * Shortcode: You can add a form to any post or page by adding the shortcode (ex. `[madmimi id=80326]`) in the page/post editor. You can find a form’s ID on the Mad Mimi Settings page.
* Template tag: You can add the following template tag into any WordPress file: `<?php madmimi_form( $form_id ); ?>`. Ex. `<?php madmimi_form( 91 ); ?>` You can find a form’s ID on the Mad Mimi Settings page.

> That's it. You're ready to go!

- [ ] FAQ

> #### What is Mad Mimi?
>
>[Mad Mimi](https://madmimi.com) is the easiest way to create, send, share and track email newsletters online. Mad Mimi is for people who want email marketing to be simple.
>
>#### Do I need a Mad Mimi account to use this plugin?
>
>Yes, this plugin requires a [Mad Mimi](https://madmimi.com) account.
>
>#### Is there a widget?
>
>Absolutely. You can use it by finding the widget called “Mad Mimi Form” under Appearance >Widgets in the WordPress Dashboard and drag it into the widget area of your choice. You can then add a title and select a form!
>
>#### Is there a shortcode?
>
>Yes! You can add a form to any post or page by adding the shortcode with the form ID (ex. `[madmimi id=80326]`) in the page/post editor. You can find a form’s ID on the Mad Mimi Settings page.
>
>#### Is there a template tag?
>
>Yup! You can add the following template tag into any WordPress file: `<?php madmimi_form( $form_id ); ?>`. Ex. `<?php madmimi_form( 91 ); ?>` You can find a form’s ID on the Mad Mimi Settings page.
>
>#### Where can I find the API Key?
>
>The API key is in your Mad Mimi account area. For more details see: [http://help.madmimi.com/where-can-i-find-my-api-key/](http://help.madmimi.com/where-can-i-find-my-api-key/)

- [ ] Screenshots, need updating once new plugin is done.
- [ ] Changelog, should mention it's forked from Mad Mimi
- [ ] Plugin Authors, Mad Mimi Plugin currently lists

> - Mad Mimi Email Marketing
> - illuminea
> - Maor Chasen
> - Rebecca Markowitz

I'm thinking that for this new version it will want to be

- GoDaddy
- Human Made

**Comment by willmot** [comment]
@susandyoung could you confirm the copy changes for the new version of the plugin, the various pieces of text are listed out the issue description above. Thanks!

**Comment by susandyoung** [comment]
Checking with our copy folks. @willmot

**Comment by willmot** [comment]
Thanks @susandyoung!

**Comment by willmot** [comment]
Now have this

**Comment by willmot** [comment]
Here's the new copy:

> **GoDaddy Email Marketing WP Plugin Copy**
> 
> What should it be officially called?
> 
> - GoDaddy Email Marketing Signup Forms
> 
> What should the plugin description be?
> 
> - Add the GoDaddy Email Marketing signup form to your WordPress site! Easy to set up, the plugin allows your site visitors to subscribe to your email lists.
> 
> Readme:
> 
> - The GoDaddy Email Marketing signup form plugin makes it easy to grow your subscribers! Use this plugin to integrate your signup forms into your WordPress site. To learn more, [pick up a GoDaddy Email Marketing account](https://www.godaddy.com/business/email-marketing) and explore.
> 
>  Once the plugin is activated, you can select and insert any of your GoDaddy Email Marketing signup forms right into your site by using a widget, shortcode, or template tag. Setup is easy; in the plugin Settings, simply enter your account email address and API key (found in the Settings section of yourGoDaddy Email Marketing account), and you're all set.
> 
> **Official GoDaddy Email Marketing Signup Forms plugin features:**
> 
> - Automatically add new forms for users to sign up to an email list of your choice
> - Insert unlimited signup forms using the widget, shortcode, or template tag
> - Use quick links to edit and preview your form in GoDaddy Email Marketing
> 
> Plugin Tags, Mad Mimi's are:
> 
> - forms, newsletter, opt-in, email marketing, signup, subscribe
> 
> Installation instructions:
> 
> 1. Upload plugin files to your plugins folder, or install using WordPress' built-in Add New Plugin installer.
> 2. Activate the plugin.
> 3. Go to the plugin Settings page (under Settings > GoDaddy Email Marketing Settings).
> 4. Enter your account email address and API key (found in the Settings section of yourGoDaddy Email Marketing account).
> 5. Click **Save Changes**.
> 
> After your account is verified, you can insert a form into your site by using a widget, shortcode, or template tag:
> 
> - **Widget**
>  Go to Appearance > Widgets, find the GoDaddy Email Marketing widget, and drag it into the widget area of your choice. You can then add a title and select a form!
> - **Shortcode**
>  Add a form to any post or page by adding the shortcode (e.g., [gem id=80326[THB1] ]) in the page/post editor. You can find a form's ID on the GoDaddy Email Marketing Settings page.
> - **Template tag**
>  Add the following template tag into any WordPress file: <?php gem\_form[THB1] ( $form\_id ); ?>.
>  For example: <?php gem\_form( 91 ); ?>
>  You can find a form's ID on the GoDaddy Email Marketing Settings page.
> 
> That's it. You're ready to go!
> 
> FAQ
> 
> **What is GoDaddy Email Marketing?**
> 
> GoDaddy Email Marketing is the easiest way to create, send, share, and track email newsletters online. It's for people who want email marketing to be simple.
> 
> **Do I need a GoDaddy Email Marketing account to use this plugin?**
> 
> Yes, this plugin requires a [GoDaddy Email Marketing](https://www.godaddy.com/business/email-marketing) account.
> 
> **Is there a widget?**
> 
> Absolutely. Use it by finding the GoDaddy Email Marketing widget under Appearance >Widgets in the WordPress Dashboard and dragging it into the widget area of your choice. You can then add a title and select a form!
> 
> **Is there a shortcode?**
> 
> Yes! You can add a form to any post or page by adding the shortcode with the form ID (e.g., [gem id=80326[THB1] ]) in the page/post editor. Form IDs are listed on the Mad Mimi Settings page.
> 
> **Is there a template tag?**
> 
> Yup! Add the following template tag into any WordPress file: <?php gem\_form[THB1] ( $form\_id ); ?>. For example: <?php gem\_form( 91 ); ?>. Form IDs are listed on the Mad Mimi Settings page.
> 
> **Where can I find the API Key?**
> 
> You can find your API key in the Settings section of yourGoDaddy Email Marketing account.
> 
> - Screenshots: need updating once new plugin is done.
> - Changelog: should mention it's forked from Mad Mimi
> - Plugin Authors: Mad Mimi Plugin currently lists
> 
> - Mad Mimi Email Marketing
> - illuminea
> - Maor Chasen
> - Rebecca Markowitz
> 
> I'm thinking that for this new version it will want to be
> 
> - GoDaddy
> - Human Made

**Comment by willmot** [comment]
Done!
