### ISSUE TITLE
New image assets

### ISSUE THREAD

**Issue by willmot** [humanmade/godaddy-email-marketing-wordpress-plugin#2]
We need:

**Plugin Banner** 

Used as the header image on the plugin directory, see here: https://wordpress.org/plugins/mad-mimi-sign-up-forms/

It will have the plugin name overlaid on the bottom left.

- [x] `banner-772x250.jpg`
- [x] `banner-1544x500.jpg` _retina_

**Plugin Icon**

Used in search results: https://wordpress.org/plugins/search.php?q=mad+mimi

The existing plugin doesn't have one either https://github.com/humanmade/madmimi-wp/issues/1

- [x] `icon-128x128.jpg`
- [x] `icon-256x256.jpg` _retina_

They can also be `.png`'s

**Comment by willmot** [comment]
Hey @saschamt, this issue lists out the assets we need at this point, if you could just attach them directly here that would be great.

**Comment by saschamt** [comment]
Hey @willmot - attached are the icons, I'll get you the banner image tomorrow. Thanks!

![icon-128x128](https://cloud.githubusercontent.com/assets/2664642/7943313/221239de-0964-11e5-8536-e39b8de94fe8.png)
![icon-256x256](https://cloud.githubusercontent.com/assets/2664642/7943314/2236fa76-0964-11e5-92fe-c90e49a242df.png)

**Comment by saschamt** [comment]
@willmot: and here's the new banner:

![banner-1544x500](https://cloud.githubusercontent.com/assets/2664642/7954440/e55672b4-09cf-11e5-9cad-cb232d8203f7.png)
![banner-772x250](https://cloud.githubusercontent.com/assets/2664642/7954441/e595772a-09cf-11e5-94ae-b8d1eb58393f.png)

**Comment by willmot** [comment]
Thanks @saschamt these look great!

**Comment by willmot** [comment]
Hey @saschamt, have realised there may have been some miss-communication here. You've only provided updated imagery for the Mad Mimi plugin, but this is the repository for the GoDaddy version. I had assumed you meant that the GoDaddy version was also going to use the Mad Mimi branding for now, but given #7 that assumption was obviously wrong! Would you be able to provide the above icon and banner sizes for the new GoDaddy version as well.

cc @susandyoung FYI

**Comment by saschamt** [comment]
Sure Tom, adding those in a couple of minutes.

**Comment by willmot** [comment]
Thanks @saschamt!

**Comment by saschamt** [comment]
Here are the assets Tom:
![128_128_icon 2x](https://cloud.githubusercontent.com/assets/2664642/8649013/34cd238c-2966-11e5-9a32-14ab63a77d89.png)
![128_128_icon](https://cloud.githubusercontent.com/assets/2664642/8649014/34f410d2-2966-11e5-8e05-339ee0768974.png)

![banner-772x250 2x](https://cloud.githubusercontent.com/assets/2664642/8649020/3bc30828-2966-11e5-93c0-5f56ca416cb5.png)
![banner-772x250](https://cloud.githubusercontent.com/assets/2664642/8649026/480e4430-2966-11e5-8b17-3548f43afe89.png)

**Comment by willmot** [comment]
Thanks @saschamt, let's go live!

**Comment by willmot** [comment]
These are live \0/
