### ISSUE TITLE
Replace Mad Mimi Imagery

### ISSUE THREAD

**Issue by willmot** [humanmade/godaddy-email-marketing-wordpress-plugin#7]
We should be using GEM imagery instead of Mad Mimi 

<img width="1228" alt="00000065" src="https://cloud.githubusercontent.com/assets/308507/8532979/1f71df3e-2432-11e5-8f6a-eebadad86304.png">

@saschamt could you provide an updated image we can use in-place of the Mimi torso / head. Thanks!

**Comment by saschamt** [comment]
Of course, @willmot 
![identity_gem_wp](https://cloud.githubusercontent.com/assets/2664642/8549509/63fa6ca4-24cb-11e5-9d24-008ebf39361f.png)

**Comment by willmot** [comment]
Thanks!

**Comment by willmot** [comment]
This is now in 
<img width="491" alt="screen shot 2015-07-07 at 19 39 15" src="https://cloud.githubusercontent.com/assets/308507/8554137/e67eac58-24df-11e5-9ed2-e084a98aceb0.png">
