### ISSUE TITLE
"Where can I find my API key?" link leads to Mad Mimi help article

### ISSUE THREAD

**Issue by susandyoung** [humanmade/godaddy-email-marketing-wordpress-plugin#9]
Referring to this link under settings: http://screencast.com/t/fv8zV7DXEa

**Comment by willmot** [comment]
@susandyoung could you get me the correct link and I'll swap it out 👍

**Comment by willmot** [comment]
Also be good to confirm that the other links are also correct (I had thought that all existing links would continue to point to MadMimi for now):

- [ ] There are 5 links in the help tab:

<img width="791" alt="screen shot 2015-07-07 at 12 24 39" src="https://cloud.githubusercontent.com/assets/308507/8545142/55d7c702-24a3-11e5-8959-023cb4f35b30.png">

Should these continue to point to Mad Mimi?

- [ ] The "edit" and "preview" links on a form point to Mad Mimi, should they?
<img width="409" alt="screen shot 2015-07-07 at 12 26 40" src="https://cloud.githubusercontent.com/assets/308507/8545148/7ad258a6-24a3-11e5-999d-92ecc8196c7a.png">

**Comment by willmot** [comment]
Here's the API link: https://gdhelp.godaddy.com/article/15909

**Comment by willmot** [comment]
Fixed in 3e6a15b

**Comment by willmot** [comment]
@susandyoung I've corrected the link to https://gdhelp.godaddy.com/article/15909, although I noticed that think is currently returning a `403 Forbidden` error, I assume this'll be fixed by launch?

Just waiting on feedback re: https://github.com/humanmade/godaddy-email-marketing-wordpress-plugin/issues/9#issuecomment-119176704 before we close this one out.

**Comment by susandyoung** [comment]
oops, that's an internal help URL. Here's the customer facing one. https://support.godaddy.com/help/article/15909/find-api-key

**Comment by willmot** [comment]
Ah ok cool, will get that switch in 👍

**Comment by willmot** [comment]
Fixed in https://github.com/humanmade/godaddy-email-marketing-wordpress-plugin/commit/1df9dddf7e863026694bfb682e54480635bb8a51

**Comment by willmot** [comment]
@susandyoung just wanted to check if you'd seen my comment about the other mad mimi help links (see https://github.com/humanmade/godaddy-email-marketing-wordpress-plugin/issues/9#issuecomment-119176704)? Should those be switched out for GoDaddy versions as well?

**Comment by susandyoung** [comment]
I did miss that comment. Thanks for pointing it out. The link to find your API key: https://gem.godaddy.com/user/edit
Where does the link that just says "Mad Mimi" point to? Is it just madmimi.com? In that case, it just just say GoDaddy and point to godaddy.com.
Mad Mimi help docs should be replaced with GoDaddy help docs. https://support.godaddy.com/
Mad Mimi blog should simply go away, there's not a GEM equivalent to point to. 
Contact Mad Mimi should say Contact GoDaddy and should also point to https://support.godaddy.com/ since it has support contact info there.

**Comment by willmot** [comment]
Thanks Susan, will get those switched out

**Comment by willmot** [comment]
> Where does the link that just says "Mad Mimi" point to? Is it just madmimi.com? In that case, it just just say GoDaddy and point to godaddy.com.

Yep that was it, have changed to GoDaddy.com

All the others are done also 👍

**Comment by willmot** [comment]
Actually one last question @susandyoung 

- [ ] The "edit" and "preview" links on a form point to Mad Mimi, should they?
<img width="409" alt="screen shot 2015-07-07 at 12 26 40" src="https://cloud.githubusercontent.com/assets/308507/8545148/7ad258a6-24a3-11e5-999d-92ecc8196c7a.png">

**Comment by susandyoung** [comment]
Good catch! The URLs should be the same except gem.godaddy.com should replace the madmimi.com part. The page URLs are structured the same across the two.

**Comment by willmot** [comment]
ok great!

**Comment by willmot** [comment]
Actually, I'm a bit confused :confused: :smile: 

So those edit links are actually returned from the API, it's not something I have control over in the plugin.

At the moment (per https://github.com/humanmade/godaddy-email-marketing-wordpress-plugin/issues/4) this new GEM plugin is still using the same `http://api.madmimi.com/` API url and so that is why the form edit links are coming back as pointing to madmimi.com.

So either https://github.com/humanmade/godaddy-email-marketing-wordpress-plugin/issues/4 is wrong and we should be using a different API url?

Or the edit form links should be left as they are, pointing back to api.madmimi.com?

**Comment by susandyoung** [comment]
Oh tricky. So by continuing to use the Mimi API URLs, we're returning Mad Mimi URLs within the plugin for the users to follow. I need to defer to @marcheiligers here.

**Comment by willmot** [comment]
Sure, @marcheiligers let me know if you need more info 👍

**Comment by marcheiligers** [comment]
That is indeed incorrect. Can you tell me which API end-point is returning those links. I'll make sure that those are updated depending on if the user is a Mimi or a GEM user.

**Comment by willmot** [comment]
Hey @marcheiligers, did a bit more digging. It seems these urls are constructed by the plugin, but the edit links are just direct calls to the API, so I assume they want to stay the same?

Here, for example, is the edit link for one of my forms: `http://api.madmimi.com/sessions/single_signon?token=REDACTED&username=willmot%40gmail.com&redirect=/signups/144593/edit`

If the API calls are all supposed to use `api.mdmimi.com` then I assume that these edit links are also supposed to continue pointing to the same place?

The preview links don't go through the API though, the form above has the preview link: `https://madmimi.com/signups/144593/join`. I've changed that to `https://gem.godaddy.com/signups/144593/join` which seems to work fine.
